# This is the configuration used to check the rubocop source code.
inherit_from: .rubocop_todo.yml
AllCops:
  TargetRubyVersion: 2.1
  Exclude:
    - 'db/**/*.rb'
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'db/**/*.rb'